# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-23 12:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hfu_cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_doctor',
            name='new_service_offered_final',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='live_doctor',
            name='new_speciality_final',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
