# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfu_cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy_cat_disease_aasociation',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('diseaseid', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ambulance',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='ambulance_type_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='ambulance_type_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='ambulanceservices',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='ambulanceservices',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='associatedoctorwithorganization',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='associatedoctorwithorganization',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='attach_dietitian_organisation',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='attach_dietitian_organisation',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='attach_therapist_organisation',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='attach_therapist_organisation',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='bloodbankservices',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='bloodbankservices',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='dietician',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='dietician',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='dietitian',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='dietitian',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='dietitian_type_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='dietitian_type_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='dietitianservices',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='dietitianservices',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='disease_category_search_mapping',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='disease_category_search_mapping',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='disease_search_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='disease_search_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='disease_type_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='disease_type_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='doc_care_services_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='doc_care_services_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='lab_accreditation_body_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='lab_accreditation_body_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='lab_branches',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='lab_branches',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='lab_department_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='lab_department_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='lab_services_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='lab_services_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='lab_test_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='lab_test_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='lab_type_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='lab_type_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='labs_plan',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='labs_plan',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='live_doctor',
            name='associated_diseases',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='live_doctor',
            name='associated_symptoms',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='medicalpharmacystore',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='medicalpharmacystore',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='medicalpharmacystoreservices',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='medicalpharmacystoreservices',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='medicalpharmacystoretype',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='medicalpharmacystoretype',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='nurse_bureau',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='nurse_bureau',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='nurse_bureau_speciality_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='nurse_bureau_speciality_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='nurse_bureauservices',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='nurse_bureauservices',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='oranisationimagery',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='oranisationimagery',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='organisation_branches',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='organisation_branches',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='organisation_categories',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='organisation_categories',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='organisation_plan',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='organisation_plan',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='organisation_profile_img',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='organisation_profile_img',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='organisation_types',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='organisation_types',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='pub_unpub_error_log',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='pub_unpub_error_log',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='rehab_speciality_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='rehab_speciality_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='rehab_type_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='rehab_type_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='rehabservices',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='rehabservices',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='symptoms_search_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='symptoms_search_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='therapist_speciality_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='therapist_speciality_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='therapist_type_master',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='therapist_type_master',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='therapists',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='therapists',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='therapistservices',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='therapistservices',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='validatebychoice',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='validatebychoice',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
