# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hfu_cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorsfeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(blank=True, help_text='Topic Title', max_length=30000, null=True)),
                ('newsfeed_image_file_name', models.CharField(blank=True, max_length=30000, null=True)),
                ('related_topics', models.TextField(blank=True, max_length=30000, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('activation_status', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('blocked_news', models.BooleanField(default=False)),
                ('publish_data', models.BooleanField(default=False)),
                ('posted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('small_description', models.CharField(blank=True, max_length=30000, null=True)),
                ('newsfeed_html_refined', models.TextField(null=True)),
                ('tag_string', models.TextField(blank=True, max_length=30000, null=True)),
                ('previous_user', models.IntegerField(null=True)),
                ('is_disable', models.BooleanField(default=False)),
                ('free_text', models.TextField(blank=True, max_length=5000, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('page_title', models.TextField(blank=True, max_length=250, null=True)),
                ('page_keywords', models.TextField(blank=True, max_length=500, null=True)),
                ('page_description', models.TextField(blank=True, max_length=800, null=True)),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('updatedAt', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hfu_cms.Live_Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(blank=True, help_text='Topic Title', max_length=30000, null=True)),
                ('doctors_category', models.CharField(blank=True, max_length=30000, null=True)),
                ('newsfeed_image_file_name', models.CharField(blank=True, max_length=30000, null=True)),
                ('related_topics', models.TextField(blank=True, max_length=30000, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('activation_status', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('blocked_news', models.BooleanField(default=False)),
                ('publish_data', models.BooleanField(default=False)),
                ('posted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('small_description', models.CharField(blank=True, max_length=30000, null=True)),
                ('newsfeed_docx_file', models.FileField(max_length=30000, null=True, upload_to=b'/var/cms/cms/media/articles/docx/newsfeed')),
                ('newsfeed_html_raw', models.TextField(null=True)),
                ('newsfeed_html_refined', models.TextField(null=True)),
                ('tag_string', models.TextField(blank=True, max_length=30000, null=True)),
                ('previous_user', models.IntegerField(null=True)),
                ('is_disable', models.BooleanField(default=False)),
                ('free_text', models.TextField(blank=True, max_length=5000, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('page_title', models.TextField(blank=True, max_length=250, null=True)),
                ('page_keywords', models.TextField(blank=True, max_length=500, null=True)),
                ('page_description', models.TextField(blank=True, max_length=800, null=True)),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('updatedAt', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of News Type', max_length=1000)),
                ('delete', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('updatedAt', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='news_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsTypeMaster'),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='resource_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hfu_cms.ValidateByChoice'),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hfu_cms.Stage'),
        ),
        migrations.AddField(
            model_name='doctorsfeed',
            name='news_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.NewsTypeMaster'),
        ),
        migrations.AddField(
            model_name='doctorsfeed',
            name='resource_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hfu_cms.ValidateByChoice'),
        ),
        migrations.AddField(
            model_name='doctorsfeed',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hfu_cms.Stage'),
        ),
    ]
