# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='newstypemaster',
            name='createdAt',
            field=models.DateTimeField(blank=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='newstypemaster',
            name='updatedAt',
            field=models.DateTimeField(blank=True, db_column='updatedAt', null=True),
        ),
    ]
